# Generated by Django 4.2.6 on 2023-10-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_demo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
